services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: aethernal-web:latest
    container_name: aethernal-web
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aethernal-app.rule=Host(`app.aethernal.me`)"
      - "traefik.http.routers.aethernal-app.entrypoints=websecure"
      - "traefik.http.routers.aethernal-app.tls=true"
      - "traefik.http.routers.aethernal-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.aethernal-app.loadbalancer.server.port=3000"
networks:
  traefik-public:
    external: true
